version: "3.7"

networks: 
  appnet:

services: 
  database:
    image: chukmunnlee/leisuredb:v1
    build:
      context: ./data
    networks:
    - appnet

  application:
    image: chukmunnlee/tvapp:v1
    build:
      context: .
    depends_on: 
    - database
    environment: 
    - APP_PORT=3000
    ports:
    - 8080-8090:3000
    networks:
    - appnet