version: "3.7"

networks: 
  appnet:

volumes:
   data-vol:

services: 
  database:
    image: chukmunnlee/leisuredb:v1
    build:
      context: ./data
    volumes:
    - data-vol:/var/lib/mysql
    networks:
    - appnet

  application:
    image: chukmunnlee/tvapp:v1
    build:
      context: .
    depends_on: 
    - database
    environment: 
    - APP_PORT=3000
    ports:
    - 80:3000
    networks:
    - appnet
